### ISSUE TITLE
Server status not being updated when WF is stopped

### ISSUE THREAD

**Issue by israel-hdez** [hawkular/hawkular-agent#312]
Steps to reproduce:

* Setup a Hawkular services instance
* Setup a WF server
* Install WF agent in the WF server connecting the agent to Hawkular services instance
* Start or restart the WF server
  * WF agent will report to Hawkular the status of the WF server.
  * If Hawkular is queried, in the properties of the server the "Server State" will be reported as "running".
* Stop gracefully or kill the WF server
  * If Hawkular is queried, in the properties of the server the "Server State" will STILL be reported as "running".
  * The "Server State" property never gets updated.

This was first reported in: https://bugzilla.redhat.com/show_bug.cgi?id=1438816

**Comment by jmazzitelli** [comment]
replying over in bugzilla. FYI: Hawkular WildFly Agent uses JIRA for bug reports: https://issues.jboss.org/projects/HWKAGENT
