### ISSUE TITLE
master maven build failure

### ISSUE THREAD

**Issue by maccloud42** [hawkular/hawkular-agent#314]
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2017-04-07T10:29:37+02:00
[INFO] Final Memory: 174M/1143M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:java (install-agent-module) on project hawkular-wildfly-agent-example-jndi: An exception occured while executing the Java class. null: InvocationTargetException: wildflyHome = /home/extanb/Documents/adnovum/IdeaProjects/hawkular-agent/hawkular-wildfly-agent-itest-parent/hawkular-wildfly-agent-example-jndi/../../../hawkular/dist/target/hawkular-1.0.0.Alpha8/hawkular-1.0.0.Alpha8 is not readable and existing directory -> [Help 1]

Its looking for a project "hawkular" which is not in git. The only checkouts I have are "hawkular-apm" and "hawkular-metrics". A hawkular Alpha version would not be acceptable in production. What should I do ?

**Comment by maccloud42** [comment]
This is using profile "dev"

**Comment by maccloud42** [comment]
Switched off "dev", had problems with "Example Custom Agent"(ECA) when building from parent, but ECA built OK on its own and then parent build could proceed

**Comment by jmazzitelli** [comment]
@maccloud42 note that the the Hawkular WildFly Agent and Hawkualr Java Agent use JIRA for bug reports: https://issues.jboss.org/projects/HWKAGENT/issues
